// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Server.Context;

#nullable disable

namespace Server.Migrations
{
    [DbContext(typeof(CommerceContext))]
    [Migration("20230530191041_initialdata")]
    partial class initialdata
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Server.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<string>("UploadDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "PRODUNO",
                            Price = 10,
                            UploadDate = "30/05/2023 04:10 PM"
                        },
                        new
                        {
                            Id = 2,
                            Category = "PRODUNO",
                            Price = 50,
                            UploadDate = "30/05/2023 04:10 PM"
                        },
                        new
                        {
                            Id = 3,
                            Category = "PRODUNO",
                            Price = 100,
                            UploadDate = "30/05/2023 04:10 PM"
                        },
                        new
                        {
                            Id = 4,
                            Category = "PRODUNO",
                            Price = 110,
                            UploadDate = "30/05/2023 04:10 PM"
                        },
                        new
                        {
                            Id = 5,
                            Category = "PRODUNO",
                            Price = 150,
                            UploadDate = "30/05/2023 04:10 PM"
                        },
                        new
                        {
                            Id = 6,
                            Category = "PRODUNO",
                            Price = 170,
                            UploadDate = "30/05/2023 04:10 PM"
                        },
                        new
                        {
                            Id = 7,
                            Category = "PRODUNO",
                            Price = 200,
                            UploadDate = "30/05/2023 04:10 PM"
                        },
                        new
                        {
                            Id = 8,
                            Category = "PRODUNO",
                            Price = 230,
                            UploadDate = "30/05/2023 04:10 PM"
                        },
                        new
                        {
                            Id = 9,
                            Category = "PRODUNO",
                            Price = 250,
                            UploadDate = "30/05/2023 04:10 PM"
                        },
                        new
                        {
                            Id = 10,
                            Category = "PRODUNO",
                            Price = 300,
                            UploadDate = "30/05/2023 04:10 PM"
                        },
                        new
                        {
                            Id = 11,
                            Category = "PRODUNO",
                            Price = 320,
                            UploadDate = "30/05/2023 04:10 PM"
                        },
                        new
                        {
                            Id = 12,
                            Category = "PRODUNO",
                            Price = 350,
                            UploadDate = "30/05/2023 04:10 PM"
                        },
                        new
                        {
                            Id = 13,
                            Category = "PRODUNO",
                            Price = 400,
                            UploadDate = "30/05/2023 04:10 PM"
                        },
                        new
                        {
                            Id = 14,
                            Category = "PRODUNO",
                            Price = 430,
                            UploadDate = "30/05/2023 04:10 PM"
                        },
                        new
                        {
                            Id = 15,
                            Category = "PRODUNO",
                            Price = 450,
                            UploadDate = "30/05/2023 04:10 PM"
                        },
                        new
                        {
                            Id = 16,
                            Category = "PRODUNO",
                            Price = 500,
                            UploadDate = "30/05/2023 04:10 PM"
                        },
                        new
                        {
                            Id = 17,
                            Category = "PRODDOS",
                            Price = 10,
                            UploadDate = "30/05/2023 04:10 PM"
                        },
                        new
                        {
                            Id = 18,
                            Category = "PRODDOS",
                            Price = 50,
                            UploadDate = "30/05/2023 04:10 PM"
                        },
                        new
                        {
                            Id = 19,
                            Category = "PRODDOS",
                            Price = 100,
                            UploadDate = "30/05/2023 04:10 PM"
                        },
                        new
                        {
                            Id = 20,
                            Category = "PRODDOS",
                            Price = 110,
                            UploadDate = "30/05/2023 04:10 PM"
                        },
                        new
                        {
                            Id = 21,
                            Category = "PRODDOS",
                            Price = 150,
                            UploadDate = "30/05/2023 04:10 PM"
                        },
                        new
                        {
                            Id = 22,
                            Category = "PRODDOS",
                            Price = 170,
                            UploadDate = "30/05/2023 04:10 PM"
                        },
                        new
                        {
                            Id = 23,
                            Category = "PRODDOS",
                            Price = 200,
                            UploadDate = "30/05/2023 04:10 PM"
                        },
                        new
                        {
                            Id = 24,
                            Category = "PRODDOS",
                            Price = 230,
                            UploadDate = "30/05/2023 04:10 PM"
                        },
                        new
                        {
                            Id = 25,
                            Category = "PRODDOS",
                            Price = 250,
                            UploadDate = "30/05/2023 04:10 PM"
                        },
                        new
                        {
                            Id = 26,
                            Category = "PRODDOS",
                            Price = 300,
                            UploadDate = "30/05/2023 04:10 PM"
                        },
                        new
                        {
                            Id = 27,
                            Category = "PRODDOS",
                            Price = 320,
                            UploadDate = "30/05/2023 04:10 PM"
                        },
                        new
                        {
                            Id = 28,
                            Category = "PRODDOS",
                            Price = 350,
                            UploadDate = "30/05/2023 04:10 PM"
                        },
                        new
                        {
                            Id = 29,
                            Category = "PRODDOS",
                            Price = 400,
                            UploadDate = "30/05/2023 04:10 PM"
                        },
                        new
                        {
                            Id = 30,
                            Category = "PRODDOS",
                            Price = 430,
                            UploadDate = "30/05/2023 04:10 PM"
                        },
                        new
                        {
                            Id = 31,
                            Category = "PRODDOS",
                            Price = 450,
                            UploadDate = "30/05/2023 04:10 PM"
                        },
                        new
                        {
                            Id = 32,
                            Category = "PRODDOS",
                            Price = 500,
                            UploadDate = "30/05/2023 04:10 PM"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
