// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Server.Context;

#nullable disable

namespace Server.Migrations
{
    [DbContext(typeof(CommerceContext))]
    partial class CommerceContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Server.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<string>("UploadDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "PRODUNO",
                            Price = 150,
                            UploadDate = "29/05/2023 11:48 PM"
                        },
                        new
                        {
                            Id = 2,
                            Category = "PRODUNO",
                            Price = 180,
                            UploadDate = "29/05/2023 11:48 PM"
                        },
                        new
                        {
                            Id = 3,
                            Category = "PRODUNO",
                            Price = 15,
                            UploadDate = "29/05/2023 11:48 PM"
                        },
                        new
                        {
                            Id = 4,
                            Category = "PRODUNO",
                            Price = 20,
                            UploadDate = "29/05/2023 11:48 PM"
                        },
                        new
                        {
                            Id = 5,
                            Category = "PRODDOS",
                            Price = 250,
                            UploadDate = "29/05/2023 11:48 PM"
                        },
                        new
                        {
                            Id = 6,
                            Category = "PRODDOS",
                            Price = 500,
                            UploadDate = "29/05/2023 11:48 PM"
                        },
                        new
                        {
                            Id = 7,
                            Category = "PRODDOS",
                            Price = 5,
                            UploadDate = "29/05/2023 11:48 PM"
                        },
                        new
                        {
                            Id = 8,
                            Category = "PRODDOS",
                            Price = 800,
                            UploadDate = "29/05/2023 11:48 PM"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
